name: Audit Bamboo Server
on:
  workflow_dispatch:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_INSTANCE_URL: ${{ vars.SHELF_INSTANCE_URL}}
  BAMBOO_ACCESS_TOKEN: ${{ secrets.BAMBOO_ACCESS_TOKEN }} 
  BAMBOO_INSTANCE_URL: "http://backstage-demo-bamboo.westeurope.cloudapp.azure.com"   
jobs:
  audit-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Install Actions Importer CLI
        run: |
          gh extension install github/gh-actions-importer

      - name: Actions Importer Ops
        run: |
          gh actions-importer update
          gh actions-importer audit bamboo --output-dir tmp/audit

      - name: Upload Logs (Backup)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: bamboo-audit-backup
          path: tmp/audit/
 
 
 