name: Audit | Bamboo
on:
  workflow_dispatch:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_INSTANCE_URL: ${{ vars.SHELF_INSTANCE_URL}}
  BAMBOO_ACCESS_TOKEN: ${{ secrets.BAMBOO_ACCESS_TOKEN }} 
  BAMBOO_INSTANCE_URL: ${{ vars.BAMBOO_INSTANCE_URL }}   
jobs:
  audit-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Install Actions Importer CLI
        run: |
          gh extension install github/gh-actions-importer

      - name: Actions Importer Ops
        run: |
          gh actions-importer update
          gh actions-importer audit bamboo --output-dir tmp/audit
          gh actions-importer forecast bamboo --project PLAN --output-dir tmp/forecast_reports/result

      - name: Upload Migration Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: bamboo-migration-audit
          path: tmp/audit/

      - name: Upload Forecast Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: bamboo-forecast-audit
          path: tmp/forecast_reports/ 
      - name: Cache Result
        uses: actions/cache@v4
        with:
          path: tmp/audit/
          key: audit-results

 