name: Create Issues | Importer Issue Ops
on:
  workflow_dispatch:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_INSTANCE_URL: ${{ vars.SHELF_INSTANCE_URL}}
  BAMBOO_ACCESS_TOKEN: ${{ secrets.BAMBOO_ACCESS_TOKEN }} 
  BAMBOO_INSTANCE_URL: ${{ vars.BAMBOO_INSTANCE_URL }}   
jobs:
  audit-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: GET All Plans | Bamboo
        run: |
          curl -X GET "${{ env.BAMBOO_INSTANCE_URL }}/rest/api/latest/plan" \
               -H "Authorization: Bearer ${{ env.BAMBOO_ACCESS_TOKEN }}"
          
 
 
 