name: Manage Build Plan Bamboo Migration
on:
    workflow_dispatch:
        inputs:
            migration_type:
                type: choice
                required: true
                options: 
                    - dry-run
                    - migrate
                description: "The migration type"
            build_plan_slug:
                type: string
                required: true
                description: "The plan's project and plan key in the format <projectKey>-<planKey>."
                default: MIG-MP
            target_repo_url:
                type: string
                required: true
                description: "The url of the target repo"
                default: https://github.com/pruebas-para-todos/target-repository
            output_directory:
                type: string
                required: true
                description: "can view the logs of the dry run and the converted workflow files in the specified output directory."
                default: tmp/output/
env:
    GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    GITHUB_INSTANCE_URL: ${{ vars.SHELF_INSTANCE_URL}}
    BAMBOO_ACCESS_TOKEN: ${{ secrets.BAMBOO_ACCESS_TOKEN }} 
    BAMBOO_INSTANCE_URL: ${{ vars.BAMBOO_INSTANCE_URL }}
jobs:
  init-migration:
    runs-on: ubuntu-latest
    steps:
        - name: Init Actions Importer CLI
          run: |
            gh extension install github/gh-actions-importer
            gh actions-importer update

        - name: init-migration
          run: |
            if [ ${{ inputs.migration_type}} == "dry-run" ]; then
                gh actions-importer ${{ inputs.migration_type }} bamboo build --plan-slug ${{ inputs.build_plan_slug}} --output-dir ${{ inputs.output_directory }}
            else
                gh actions-importer ${{ inputs.migration_type }} bamboo build --plan-slug ${{ inputs.build_plan_slug}} --target-url ${{ inputs.target_repo_url }} --output-dir ${{ inputs.output_directory }}
            fi

        - name: Upload Logs
          if: ${{ inputs.migration_type}} == "dry-run"
          uses: actions/upload-artifact@v4
          with:
            name: bamboo-logs-dry-run # Generar una fecha de logs o algo identificativo
            path: ${{ inputs.output_directory }}


# Dry run build plan
# gh actions-importer dry-run bamboo build --plan-slug :my_plan_slug --output-dir tmp/dry-run

# Production build plan
# gh actions-importer migrate bamboo build --plan-slug :my_plan_slug --target-url :target_url --output-dir tmp/migrate



# Dry run deployment project
# gh actions-importer dry-run bamboo deployment --deployment-project-id :my_deployment_project_id --output-dir tmp/dry-run

# Production deployment project
# gh actions-importer migrate bamboo deployment --deployment-project-id :my_deployment_project_id --target-url :target_url --output-dir tmp/migrate