name: Migration-Bitbucket-Repositories
permissions: write-all
on:
  workflow_dispatch:
    # inputs:
    #   repository_list_path:
    #     description: 'The repository path of json repositories list'
    #     required: false
    #     type: string

      # INSTALL DEPENDENCIES
      # LOGIN BITBUCKET 
      # Login Github
      # Recorrer listado repos
        # Obtener ref repo y clonarlo
        # Crear nuevo repositorio en Github con el mismo nombre
        # Subir contenido clonado en local
      # Correr herramienta migracion bamboo pipelines y analizar o ejecutar
      
        
jobs:
  get-bitbucket-repos:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: repo-list
      JSON_LIST_PATH: repos
    outputs:
      repo-list: ${{steps.repo.outputs.repo-list}}
    steps:
    - name: Checkout REPO-LIST
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.REPO_PATH }}
        ref: main
        sparse-checkout: |
          ${{ env.JSON_LIST_PATH }}/repos.json
    - name: Get Repos
      id: repo
      working-directory: ${{ env.REPO_PATH }}/${{env.JSON_LIST_PATH}}
      run: |
        LIST=$(jq -c '.' repos.json)
        echo $LIST
        echo "repo-list=$LIST" >> $GITHUB_OUTPUT
      
    # - name: Get List repositories
    #   run: |
    #     curl --request GET \
    #       --url 'https://api.bitbucket.org/2.0/repositories/noeorgagutierrez' \
    #       --header 'Authorization: Bearer <access_token>' \ #Falta Token por ser premium feature, un acces key no se si es posible
    #       --header 'Accept: application/json'
  generate-repos:
    runs-on: ubuntu-latest
    needs: get-bitbucket-repos
    strategy:
      matrix: ${{ needs.get-bitbucket-repos.outputs.repo-list }}
    steps:
      - name: Print name
        run: |
          echo ${{ matrix.name }}
    # - name: Create repository in Github
    #   run: |
    #     curl -L \
    #     -X POST \
    #     -H "Accept: application/vnd.github+json" \
    #     -H "Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}" \
    #     -H "X-GitHub-Api-Version: 2022-11-28" \
    #     https://api.github.com/orgs/Alberto-Molina-nttdata/repos \
    #     -d '{"name":"${{ matrix.name }}","description":"This is your ${{ matrix.name }} repository","homepage":"https://github.com","private":true,"has_issues":true,"has_projects":true,"has_wiki":true,"auto_init":true}'
    
    
    # - name: Clone Bitbucket repository
    #   run: |
    #     git clone --mirror https://amolinab1@bitbucket.org/noeorgagutierrez/${{ matrix.name }}.git
    #     cd frontend-angular.git
    #     git remote set-url --push origin https://${{ secrets.API_TOKEN_GITHUB }}@github.com/Alberto-Molina-nttdata/${{ matrix.name }}.git
    #     git push --mirror --force origin
    #     echo "prueba"
