name: Migration-Bitbucket-Repositories
permissions: write-all
on:
  workflow_dispatch:
# Variables usadas en los dos jobs
env:
  BITBUCKET_ORG_NAME: noeorgagutierrez
  GITHUB_ORG_NAME: ${{ github.repository_owner }}
jobs:
  get-bitbucket-repos:
    runs-on: ubuntu-latest
    env:
      # Variables usadas para probar la lista de repos
      REPO_PATH: repo-list
      JSON_LIST_PATH: repos
      JSON_NAME: repos.json
      # Variables que se usarán más adelante para hacer la llamada a la API de Bitbucket
      BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
    outputs:
      repo-list: ${{steps.repo.outputs.repo-list}}
    steps:
    - name: Checkout REPO-LIST
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.REPO_PATH }}
        ref: main
        sparse-checkout: |
          ${{ env.JSON_LIST_PATH }}/${{ env.JSON_NAME }}
    - name: Get Repos
      id: repo
      working-directory: ${{ env.REPO_PATH }}/${{env.JSON_LIST_PATH}}
      run: |
        LIST=$(jq -c '.' ${{ env.JSON_NAME }})
        echo $LIST
        echo "repo-list=$LIST" >> $GITHUB_OUTPUT
    # - name: GET Request
    #   run: |
    #     curl --request GET \
    #       --url 'https://api.bitbucket.org/2.0/repositories/${{ env.BITBUCKET_ORG_NAME }}' \
    #       --header 'Authorization: Bearer ${{ env.BITBUCKET_TOKEN }}' \ #Falta Token por ser premium feature, un acces key no se si es posible
    #       --header 'Accept: application/json'
  generate-repos:
    runs-on: ubuntu-latest
    needs: get-bitbucket-repos
    permissions: write-all
    continue-on-error: true
    strategy:
      matrix: 
        repo: ${{fromJson(needs.get-bitbucket-repos.outputs.repo-list)}} 
    steps:
    - name: Create repository in Github
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/orgs/${{ env.GITHUB_ORG_NAME }}/repos \
        -d '{"name":"${{ matrix.repo.name }}","description":"This is your ${{ matrix.repo.name }} repository","homepage":"https://github.com","private":false,"has_issues":true,"has_projects":true,"has_wiki":true}'
    - name: Clone Bitbucket repository
      run: |
        git clone --mirror https://amolinab1@bitbucket.org/${{ env.ORG_NAME }}/${{ matrix.repo.name }}.git
        cd frontend-angular.git
        git remote set-url --push origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.GITHUB_ORG_NAME }}/${{ matrix.repo.name }}.git
        git push --mirror --force origin
        echo "prueba"
