name: RU | Single Deployment
on:
    workflow_call:
        inputs:
            migration_type:
                type: string
                required: true
                description: "The migration type"
            deployment_project_id:
                type: string
                required: true
                description: "The ID of the deployment project you are converting"
            target_repo_url:
                type: string
                required: true
                description: "The url of the target repo"
                default: https://github.com/pruebas-para-todos/Migration-Bitbucket-Bamboo
            output_directory:
                type: string
                required: true
                description: "Can view the logs of the dry run and the converted workflow files in the specified output directory."
                default: tmp/output/
            
env:
    GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    GITHUB_INSTANCE_URL: ${{ vars.SHELF_INSTANCE_URL}}
    BAMBOO_ACCESS_TOKEN: ${{ secrets.BAMBOO_ACCESS_TOKEN }} 
    BAMBOO_INSTANCE_URL: ${{ vars.BAMBOO_INSTANCE_URL }}
jobs:
  init-migration:
    runs-on: ubuntu-latest
    steps:
        - name: Init Actions Importer CLI
          run: |
            gh extension install github/gh-actions-importer
            gh actions-importer update

        - name: init-migration
          run: |
            if [ ${{ inputs.migration_type}} == "dry-run" ]; then
                gh actions-importer ${{ inputs.migration_type }} bamboo deployment --deployment-project-id ${{ inputs.deployment_project_id }} --output-dir ${{ inputs.output_directory }}
            else
                gh actions-importer ${{ inputs.migration_type }} bamboo deployment --deployment-project-id ${{ inputs.deployment_project_id }} --target-url ${{ inputs.target_repo_url }} --output-dir ${{ inputs.output_directory }}
            fi

        - name: Upload Logs
          if: ${{ always() }}
          uses: actions/upload-artifact@v4
          with:
            name: "Deployment ${{ inputs.deployment_project_id}}"
            path: ${{ inputs.output_directory }}